services:
  playground:
    container_name: playground
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: opensuse/tumbleweed:latest
    stop_signal: SIGKILL
    privileged: true
    stdin_open: true
    tty: true
    # Mount your custom hooks and directories here:
    #volumes:
    #  - /etc/containers/playground/setup.sh:/usr/libexec/setup.sh:ro
    #  - /etc/containers/playground/main.sh:/usr/libexec/main.sh:ro
    #  - /var/containers/playground:/mnt:rw
